info:
  contact: {}
  license: {}
paths:
  /api/addNoticePoint:
    post:
      parameters:
      - description: 名称
        in: formData
        name: name
        required: true
        type: string
      - description: 类型
        in: formData
        name: type
        required: true
        type: integer
      - description: 纬度
        in: formData
        name: coordinateX
        required: true
        type: string
      - description: 经度
        in: formData
        name: coordinateY
        required: true
        type: string
      - description: 当前印象
        in: formData
        name: feel_now
        type: integer
      summary: 添加印象点
  /api/addProject:
    post:
      description: 添加项目
      parameters:
      - description: data
        in: formData
        name: data
        required: true
        type: string
      summary: 新建项目
  /api/login:
    post:
      consumes:
      - multipart/form-data
      description: 登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      produces:
      - application/json
      summary: 登录接口
swagger: "2.0"
