info:
  contact: {}
  license: {}
paths:
  /api/login:
    post:
      description: 登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      summary: 登录接口
swagger: "2.0"
